version: "3"

services:
  node-p2p-service:
    image: p2p:v1.0.0
    container_name: p2p-container
    build:
      context: .
      dockerfile: Imagefile
      target: deploy
    environment:
      - PORT=443
    ports:
      - 443:443
    volumes:
      # - ./certs:/usr/app/certs:delegated # not working
      - ./src:/usr/app/src:cached
      - ./build:/usr/app/build:delegated
